server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: "jdbc:mysql://127.0.0.1:3306/example"
      username: user
      password: password
      auto-commit: false
      
